### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by ghost** [Lukx19/dynamic_slam#1]

**Comment by yalan2017** [comment]
hi
CMake Error at ndt_gslam_attachments-master/ndt_gslam/cmake-modules/FindG2O.cmake:85 (message):
  Could not find libg2o!
i have this problem how can i fix it.
TKs

**Comment by Lukx19** [comment]
Install libg20
apt install ros-kinetic-libg2o 

I will write full installation guide shortly.
